# embed-ui-assets.cmake -- `cmake -P` script that walks the ui/ tree and
# writes a generated `.cc` TU embedding every front-end asset (.js/.css)
# as a byte array, then REGISTERS the table with UiViewRegistry at
# static-init time.
#
# This is what "packaged with libvpipe, not the web-ui app" means: the
# view's JavaScript rides in the same shared library as the stage it
# belongs to, and any front-end application serves it by asking the
# registry -- there is no asset tree on disk to install and no app-side
# copy to keep in sync.
#
# Each file maps to a URL path = "/ui" + its path relative to UI_DIR:
#   <UI_DIR>/sdk/view-channel.js
#       -> "/ui/sdk/view-channel.js"
#   <UI_DIR>/stages/preview/preview-view.js
#       -> "/ui/stages/preview/preview-view.js"
#
# Required -D inputs:
#   UI_DIR -- absolute path to the ui/ source root
#   OUTPUT -- absolute path of the .cc file to write

if(NOT DEFINED UI_DIR)
  message(FATAL_ERROR "embed-ui-assets.cmake: -D UI_DIR=... required")
endif()
if(NOT DEFINED OUTPUT)
  message(FATAL_ERROR "embed-ui-assets.cmake: -D OUTPUT=... required")
endif()

# Front-end sources only: the C++ in this tree builds normally and must
# never be embedded as an asset.
file(GLOB_RECURSE ASSET_FILES
     "${UI_DIR}/*.js" "${UI_DIR}/*.css" "${UI_DIR}/*.html"
     "${UI_DIR}/*.svg")
list(SORT ASSET_FILES)

set(ARRAYS "")
set(ROWS "")
set(IDX 0)
foreach(f ${ASSET_FILES})
  file(RELATIVE_PATH rel "${UI_DIR}" "${f}")
  file(READ "${f}" BYTES HEX)
  string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," CSV "${BYTES}")
  string(APPEND ARRAYS
    "const unsigned char kA${IDX}[] = {\n${CSV}\n};\n")
  string(APPEND ROWS
    "  { \"/ui/${rel}\", kA${IDX}, sizeof(kA${IDX}) },\n")
  math(EXPR IDX "${IDX} + 1")
endforeach()

set(HEADER
"// Auto-generated by ui/cmake/embed-ui-assets.cmake. Do not edit.
//
// Embeds the stage-provided front-end assets under ${UI_DIR} into
// libvpipe and publishes them through UiViewRegistry, so a front-end
// application can serve a stage's own GUI view without shipping a copy
// of it.

#include \"ui/ui-view-registry.h\"

#include <cstddef>

namespace vpipe {
namespace {
")

if(IDX EQUAL 0)
  # No assets found: emit a valid TU that registers nothing.
  file(WRITE "${OUTPUT}" "${HEADER}
const int kRegistered = [] { return 0; }();

}  // namespace
}  // namespace vpipe
")
  return()
endif()

file(WRITE "${OUTPUT}" "${HEADER}
${ARRAYS}
// Static storage duration: the registry keeps pointers into this table.
const UiViewAsset kAssets[] = {
${ROWS}};

const int kRegistered = [] {
  UiViewRegistry::get().register_assets(
      kAssets, sizeof(kAssets) / sizeof(kAssets[0]));
  return 0;
}();

}  // namespace
}  // namespace vpipe
")
