# embed-web-assets.cmake -- `cmake -P` script that walks a web asset
# directory and writes a generated `.cc` TU embedding every file as a
# byte array, plus a path -> bytes lookup
# (vpipe::webui::find_embedded_asset). This lets a packaged
# vpipe-web-ui serve its UI from memory with no doc-root on disk.
#
# Each file maps to a URL path relative to WEB_DIR, e.g.
#   <WEB_DIR>/index.html   -> "/index.html"
#   <WEB_DIR>/js/app.js     -> "/js/app.js"
#
# Required -D inputs:
#   WEB_DIR -- absolute path to the asset root
#   OUTPUT  -- absolute path of the .cc file to write

if(NOT DEFINED WEB_DIR)
  message(FATAL_ERROR "embed-web-assets.cmake: -D WEB_DIR=... required")
endif()
if(NOT DEFINED OUTPUT)
  message(FATAL_ERROR "embed-web-assets.cmake: -D OUTPUT=... required")
endif()

file(GLOB_RECURSE ASSET_FILES "${WEB_DIR}/*")
list(SORT ASSET_FILES)

set(ARRAYS "")
set(ROWS "")
set(IDX 0)
foreach(f ${ASSET_FILES})
  file(RELATIVE_PATH rel "${WEB_DIR}" "${f}")
  file(READ "${f}" BYTES HEX)
  string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," CSV "${BYTES}")
  string(APPEND ARRAYS
    "const unsigned char kA${IDX}[] = {\n${CSV}\n};\n")
  string(APPEND ROWS
    "  { \"/${rel}\", { kA${IDX}, sizeof(kA${IDX}) } },\n")
  math(EXPR IDX "${IDX} + 1")
endforeach()

set(HEADER
"// Auto-generated by embed-web-assets.cmake. Do not edit.
//
// Embeds the web-ui asset tree (${WEB_DIR}) into the binary so a
// packaged build can serve the UI from memory.

#include \"apps/web-ui/embedded-assets.h\"

#include <cstddef>
#include <string_view>

namespace vpipe::webui {
")

if(IDX EQUAL 0)
  # No assets found: emit a valid TU that reports an empty registry.
  file(WRITE "${OUTPUT}" "${HEADER}
const EmbeddedAsset* find_embedded_asset(std::string_view) { return nullptr; }
std::size_t embedded_asset_count() { return 0; }

}  // namespace vpipe::webui
")
  return()
endif()

file(WRITE "${OUTPUT}" "${HEADER}
namespace {

${ARRAYS}
struct Row {
  std::string_view path;
  EmbeddedAsset    asset;
};

const Row kRows[] = {
${ROWS}};

}  // namespace

const EmbeddedAsset*
find_embedded_asset(std::string_view path)
{
  for (const auto& r : kRows) {
    if (r.path == path) { return &r.asset; }
  }
  return nullptr;
}

std::size_t
embedded_asset_count()
{
  return sizeof(kRows) / sizeof(kRows[0]);
}

}  // namespace vpipe::webui
")
