// VDN-H3 hybrid-attention geometry, against goldens generated by running
// OpenVDN's own reference modules (window.py, scan.py, flex_attention.py).
//
// WHY THIS IS THE FIRST THING WITH A TEST. VDN's two branches PARTITION
// the key set: the softmax window covers a band of whole frames around
// each query and the linear branch carries exactly the complement. Every
// number here is an index into that agreement, and every way of getting
// one wrong is silent -- a frame counted twice is a plausible image, a
// frame counted by neither is a slightly worse plausible image. None of
// it needs weights or a GPU, which is why it can be pinned before any of
// the model exists.
//
// The goldens come out of the reference itself rather than from reading
// the paper: `~/dock/dump/vpipe-test/vdn/gen_goldens.py geometry`, which
// imports the cloned repo and calls window_bounds / _gather_indices /
// _gather_body. A golden written from the description would reproduce
// this reader's understanding, which is the thing under test.

#include "minitest.h"
#include <algorithm>

#include "common/flex-data.h"
#include "generative-models/minimax-h3/vdn-geometry.h"

#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <string>
#include <vector>

using namespace vpipe;
using namespace vpipe::genai::minimax_h3;

namespace {

std::string
golden_path_()
{
  if (const char* e = std::getenv("VPIPE_VDN_GOLDEN")) { return e; }
  const char* home = std::getenv("HOME");
  if (home == nullptr) { return ""; }
  return std::string(home) + "/dock/dump/vpipe-test/vdn/vdn-geometry.json";
}

std::vector<double>
reals_(const FlexData& v)
{
  std::vector<double> out;
  FlexData owner = v;              // as_array() is a VIEW: keep the owner
  if (!owner.is_array()) { return out; }
  auto a = owner.as_array();
  out.reserve(a.size());
  for (std::size_t i = 0; i < a.size(); ++i) {
    out.push_back(a.at(i).as_real(0.0));
  }
  return out;
}

std::vector<char>
bools_(const FlexData& v)
{
  std::vector<char> out;
  FlexData owner = v;
  if (!owner.is_array()) { return out; }
  auto a = owner.as_array();
  out.reserve(a.size());
  for (std::size_t i = 0; i < a.size(); ++i) {
    out.push_back((char)(a.at(i).as_bool(false) ? 1 : 0));
  }
  return out;
}

std::vector<int>
ints_(const FlexData& v)
{
  std::vector<int> out;
  FlexData owner = v;
  if (!owner.is_array()) { return out; }
  auto a = owner.as_array();
  out.reserve(a.size());
  for (std::size_t i = 0; i < a.size(); ++i) {
    out.push_back((int)a.at(i).as_int(0));
  }
  return out;
}

// Largest absolute difference, or -1 when the sizes disagree.
double
max_abs_diff_(const std::vector<float>& got, const std::vector<double>& want)
{
  if (got.size() != want.size()) { return -1.0; }
  double worst = 0.0;
  for (std::size_t i = 0; i < got.size(); ++i) {
    worst = std::max(worst, std::fabs((double)got[i] - want[i]));
  }
  return worst;
}

std::vector<vdn::Bound>
bounds_of_(const FlexData& v)
{
  std::vector<vdn::Bound> out;
  FlexData owner = v;
  if (!owner.is_array()) { return out; }
  auto a = owner.as_array();
  for (std::size_t i = 0; i < a.size(); ++i) {
    FlexData pair = a.at(i);
    auto p = pair.as_array();
    if (p.size() != 2) { return {}; }
    out.push_back({(int)p.at(0).as_int(0), (int)p.at(1).as_int(0)});
  }
  return out;
}

}  // namespace

TEST(vdn_geometry, matches_the_reference)
{
  const std::string path = golden_path_();
  std::ifstream in(path);
  if (!in) {
    // Absent goldens SKIP rather than fail: they are a dock-side
    // artifact, not a repo one. Regenerate with gen_goldens.py.
    return;
  }
  FlexData doc = FlexData::from_json(in);
  ASSERT_TRUE(doc.is_object());
  if (!doc.is_object()) { return; }
  auto root = doc.as_object();
  ASSERT_TRUE(root.contains("cases"));
  if (!root.contains("cases")) { return; }
  FlexData cases_owner = root.at("cases");
  auto cases = cases_owner.as_array();
  EXPECT_TRUE(cases.size() > 0);

  int n_bounds = 0, n_gather = 0, n_mask = 0;
  for (std::size_t ci = 0; ci < cases.size(); ++ci) {
    FlexData c_owner = cases.at(ci);
    auto c = c_owner.as_object();
    const std::string kind(c.at("kind").as_string(""));

    if (kind == "window_bounds") {
      ++n_bounds;
      const int F = (int)c.at("num_frames").as_int(0);
      const std::vector<vdn::Bound> got = vdn::window_bounds(
          F, (int)c.at("radius").as_int(0), (int)c.at("chunk").as_int(0));
      const std::vector<vdn::Bound> want = bounds_of_(c.at("bounds"));
      ASSERT_TRUE(got.size() == want.size());
      if (got.size() != want.size()) { continue; }
      bool ok = true;
      for (std::size_t i = 0; i < got.size(); ++i) {
        ok = ok && got[i].lo == want[i].lo && got[i].hi == want[i].hi;
      }
      EXPECT_TRUE(ok);
      continue;
    }

    if (kind == "gather") {
      ++n_gather;
      const int F  = (int)c.at("num_frames").as_int(0);
      const int H  = (int)c.at("heads").as_int(0);
      const int dk = (int)c.at("d_k").as_int(0);
      const int dv = (int)c.at("d_v").as_int(0);
      const std::vector<vdn::Bound> bounds = bounds_of_(c.at("bounds"));
      const vdn::GatherIndex idx = vdn::gather_indices(bounds, F);

      EXPECT_TRUE(idx.before_idx == ints_(c.at("before_idx")));
      EXPECT_TRUE(idx.after_idx == ints_(c.at("after_idx")));
      EXPECT_TRUE(idx.bridge_before == ints_(c.at("bridge_before")));
      EXPECT_TRUE(idx.bridge_after == ints_(c.at("bridge_after")));
      const std::vector<char> hb = bools_(c.at("has_before"));
      const std::vector<char> ha = bools_(c.at("has_after"));
      bool flags_ok = hb == idx.has_before && ha == idx.has_after;
      EXPECT_TRUE(flags_ok);
      if (!flags_ok) {
        std::printf("[vdn_geometry] has_before/has_after mismatch at F=%d\n",
                    (int)c.at("num_frames").as_int(0));
      }

      std::vector<double> alpha_d  = reals_(c.at("alpha"));
      std::vector<double> prefix_d = reals_(c.at("prefix"));
      std::vector<double> suffix_d = reals_(c.at("suffix"));
      std::vector<float> alpha(alpha_d.begin(), alpha_d.end());
      std::vector<float> prefix(prefix_d.begin(), prefix_d.end());
      std::vector<float> suffix(suffix_d.begin(), suffix_d.end());
      std::vector<float> text;
      if (c.contains("text_state")) {
        std::vector<double> t = reals_(c.at("text_state"));
        text.assign(t.begin(), t.end());
      }
      const std::size_t n_out =
          (std::size_t)F * H * (std::size_t)dv * (std::size_t)dk;

      for (int bridge = 0; bridge < 2; ++bridge) {
        for (int with_text = 0; with_text < 2; ++with_text) {
          const std::string key = std::string("out_")
              + (bridge != 0 ? "alpha" : "none") + "_"
              + (with_text != 0 ? "text" : "notext");
          if (!c.contains(key)) { continue; }
          std::vector<float> out(n_out, 0.0f);
          vdn::gather_linear_state(
              prefix.data(), suffix.data(), alpha.data(), idx, F, H, dv, dk,
              bridge != 0, with_text != 0 ? text.data() : nullptr,
              out.data());
          const std::vector<double> want = reals_(c.at(key));
          const double worst = max_abs_diff_(out, want);
          // fp32 against the reference's fp32: the bridge is an
          // exp of a difference of log-prefix sums either side, so
          // this is rounding, not method.
          const bool close = worst >= 0.0 && worst < 2e-5;
          EXPECT_TRUE(close);
          if (!close) {
            std::printf("[vdn_geometry] %s F=%d: %zu got vs %zu want, "
                        "worst |d| %g\n", key.c_str(), F, out.size(),
                        want.size(), worst);
          }
        }
      }
      continue;
    }

    if (kind == "window_mask") {
      ++n_mask;
      vdn::WindowMask mask;
      mask.seq_len          = (int)c.at("seq_len").as_int(0);
      mask.video_start      = (int)c.at("video_start").as_int(0);
      mask.num_frames       = (int)c.at("num_frames").as_int(0);
      mask.tokens_per_frame = (int)c.at("tokens_per_frame").as_int(0);
      mask.bounds           = bounds_of_(c.at("bounds"));
      ASSERT_TRUE(vdn::parse_anchor_frames(
          std::string(c.at("anchor_frames").as_string("")), &mask.anchors));

      FlexData runs_owner = c.at("runs");
      auto runs = runs_owner.as_array();
      ASSERT_TRUE((int)runs.size() == mask.seq_len);
      if ((int)runs.size() != mask.seq_len) { continue; }
      long long allowed = 0;
      bool ok = true;
      for (int q = 0; q < mask.seq_len && ok; ++q) {
        // Rebuild this query row's allowed runs and compare.
        std::vector<int> flat;
        int start = -1;
        for (int k = 0; k <= mask.seq_len; ++k) {
          const bool on = k < mask.seq_len && mask.allows(q, k);
          if (on && start < 0) { start = k; }
          else if (!on && start >= 0) {
            flat.push_back(start);
            flat.push_back(k - start);
            allowed += k - start;
            start = -1;
          }
        }
        FlexData row_owner = runs.at((std::size_t)q);
        auto row = row_owner.as_array();
        ok = flat.size() == row.size() * 2;
        for (std::size_t r = 0; ok && r < row.size(); ++r) {
          FlexData pr = row.at(r);
          auto p = pr.as_array();
          ok = p.size() == 2 && flat[2 * r] == (int)p.at(0).as_int(-1)
               && flat[2 * r + 1] == (int)p.at(1).as_int(-1);
        }
      }
      EXPECT_TRUE(ok);
      EXPECT_TRUE(allowed == (long long)c.at("allowed_pairs").as_int(-1));
      continue;
    }
  }
  // The counts are the guard against a golden file that parsed but said
  // nothing -- a skipped `kind` would otherwise read as a clean pass.
  EXPECT_TRUE(n_bounds >= 8);
  EXPECT_TRUE(n_gather >= 3);
  EXPECT_TRUE(n_mask >= 8);
}

TEST(vdn_geometry, anchor_skip_rebases_the_window)
{
  // The kBoth partner: frames 0 and F-1 leave the branch's input, so the
  // branch runs over F-2 frames and every bound shifts by one. Getting
  // this wrong reads the state of the wrong frame -- an off-by-one in a
  // recurrence, which looks like a slightly blurry render.
  const std::vector<vdn::Bound> b = vdn::window_bounds(12, 1, 5);
  const std::vector<vdn::Bound> r = vdn::rebase_for_anchor_skip(b, 12);
  ASSERT_TRUE(r.size() == 10);
  if (r.size() != 10) { return; }
  bool ok = true;
  for (std::size_t i = 0; i < r.size(); ++i) {
    ok = ok && r[i].lo == b[i + 1].lo - 1 && r[i].hi == b[i + 1].hi - 1;
  }
  EXPECT_TRUE(ok);
  // The anchors ARE the clip: nothing left to scan.
  EXPECT_TRUE(vdn::rebase_for_anchor_skip(vdn::window_bounds(2, 1, 5), 2)
                  .empty());
  EXPECT_TRUE(vdn::rebase_for_anchor_skip(vdn::window_bounds(1, 1, 5), 1)
                  .empty());
}

TEST(vdn_geometry, anchor_mode_names_round_trip)
{
  // An unrecognised mode must NOT fall back to a default: the mode is a
  // cross-branch fact (kBoth is what lets the linear branch drop the two
  // anchor frames), so a silent default mis-partitions the attention.
  const char* names[] = {"none", "columns", "rows", "both"};
  bool ok = true;
  for (const char* n : names) {
    vdn::AnchorFrames m = vdn::AnchorFrames::kNone;
    ok = ok && vdn::parse_anchor_frames(n, &m)
         && std::string(vdn::anchor_frames_name(m)) == n;
  }
  EXPECT_TRUE(ok);
  vdn::AnchorFrames unused = vdn::AnchorFrames::kBoth;
  EXPECT_FALSE(vdn::parse_anchor_frames("", &unused));
  EXPECT_FALSE(vdn::parse_anchor_frames("column", &unused));
  EXPECT_FALSE(vdn::parse_anchor_frames("BOTH", &unused));
}

TEST(vdn_geometry, block_spans_cover_every_key_the_mask_allows)
{
  // THE ONLY SAFETY A BLOCK LIST HAS. It is a second representation of
  // the same mask, coarser in one direction and required to be exact in
  // the other: every key the mask allows must lie in some block the list
  // names (miss one and attention silently drops it), and the list must
  // be ASCENDING and duplicate-free (the kernel's loaders only move
  // forward, so a repeat reads the wrong bytes for the rest of the row).
  //
  // The reverse containment is NOT required and must not be asserted:
  // the list is rounded outward to whole key blocks, so it names keys
  // the mask forbids on purpose -- the kernel masks those element by
  // element. That is exactly why this checks coverage and ordering
  // rather than equality.
  //
  // Same sweep the span form gets, because the two are the same kind of
  // claim: every anchor mode x {chunk 0, 5} x {radius 0, 1, 2} x a
  // frame count that makes the window bite.
  using AF = vdn::AnchorFrames;
  const AF modes[] = {AF::kNone, AF::kColumns, AF::kRows, AF::kBoth};
  const int chunks[] = {0, 5};
  const int radii[] = {0, 1, 2};
  const int frames[] = {1, 2, 3, 9, 17};
  // Deliberately not multiples of each other: a query block that never
  // straddles a frame boundary would leave the union untested, and 32/16
  // against 6 tokens a frame guarantees it does.
  const int bqs[] = {32, 16};
  const int bks[] = {16, 8};

  int cases = 0, checked = 0;
  for (AF am : modes) {
    for (int ch : chunks) {
      for (int rad : radii) {
        for (int F : frames) {
          for (int bi = 0; bi < 2; ++bi) {
            vdn::WindowMask m;
            m.tokens_per_frame = 6;
            m.video_start = 7;              // text rows before the video
            m.num_frames = F;
            m.anchors = am;
            m.bounds = vdn::window_bounds(F, rad, ch);
            m.seq_len = m.video_start + F * m.tokens_per_frame + 5;
            const vdn::BlockSpans bs =
                vdn::build_block_spans(m, bqs[bi], bks[bi]);
            ++cases;

            const int nq = (m.seq_len + bqs[bi] - 1) / bqs[bi];
            ASSERT_TRUE((int)bs.off.size() == nq + 1);
            if ((int)bs.off.size() != nq + 1) { return; }
            for (int qb = 0; qb < nq; ++qb) {
              const int b0 = bs.off[(std::size_t)qb];
              const int b1 = bs.off[(std::size_t)qb + 1];
              bool ordered = true;
              for (int i = b0 + 1; i < b1; ++i) {
                ordered = ordered && bs.blocks[(std::size_t)i]
                                         > bs.blocks[(std::size_t)i - 1];
              }
              EXPECT_TRUE(ordered);
              for (int r = qb * bqs[bi];
                   r < std::min((qb + 1) * bqs[bi], m.seq_len); ++r) {
                for (int k = 0; k < m.seq_len; ++k) {
                  if (!m.allows(r, k)) { continue; }
                  const int want = k / bks[bi];
                  bool found = false;
                  for (int i = b0; i < b1 && !found; ++i) {
                    found = bs.blocks[(std::size_t)i] == want;
                  }
                  EXPECT_TRUE(found);
                  ++checked;
                  if (!found) {
                    std::printf("[vdn_geometry] block spans miss q %d k %d "
                                "(mode %d chunk %d radius %d F %d "
                                "bq %d bk %d)\n", r, k, (int)am, ch, rad, F,
                                bqs[bi], bks[bi]);
                    return;
                  }
                }
              }
            }
          }
        }
      }
    }
  }
  std::printf("[vdn_geometry] block spans: %d configurations, %d allowed "
              "pairs all covered\n", cases, checked);
  EXPECT_TRUE(cases == 240);
}

TEST(vdn_geometry, the_window_bites_at_video_geometry_and_not_before)
{
  // WHEN THE BLOCK-SPARSE KERNEL IS WORTH TAKING, reported rather than
  // asserted tightly, because it is the answer to a question that gets
  // asked from a measurement at the wrong size.
  //
  // At the geometry the unit tests can afford -- a couple of thousand
  // rows -- the window covers most of the clip and the sparse kernel
  // wins on the MMA alone. The sparsity only bites when the clip is
  // many windows long, which is exactly video geometry and exactly what
  // no test here runs. So the ratio is computed from the GEOMETRY, which
  // needs no weights and no GPU.
  struct Case { const char* name; int frames; int tpf; int text; };
  const Case cases[] = {
      {"unit test (20 frames of 64)", 20, 64, 96},
      {"960x544, 121 latent frames", 121, 1020, 96},
      {"1280x720, 121 latent frames", 121, 1800, 96},
  };
  for (const Case& c : cases) {
    vdn::WindowMask m;
    m.tokens_per_frame = c.tpf;
    m.video_start = c.text;
    m.num_frames = c.frames;
    m.anchors = vdn::AnchorFrames::kBoth;
    m.bounds = vdn::window_bounds(c.frames, 1, 5);     // the released config
    m.seq_len = c.text + c.frames * c.tpf;
    const vdn::BlockSpans bs = vdn::build_block_spans(m, 32, 16);
    const std::size_t nq = bs.off.size() - 1;
    const std::size_t nk = (std::size_t)((m.seq_len + 15) / 16);
    const double pct = 100.0 * (double)bs.blocks.size()
                       / (double)(nq * nk);
    std::printf("[vdn_geometry] %-28s seq %7d: %.1f%% of the key blocks\n",
                c.name, m.seq_len, pct);
    // Only a sanity bracket: the window can never grow the work, and it
    // can never drop the global rows every query reads.
    EXPECT_TRUE(pct > 0.0 && pct <= 100.0);
  }
}

TEST(vdn_geometry, what_the_block_list_costs_the_windowed_kernel)
{
  // WHERE THE BLOCK-SPARSE KERNEL'S REMAINING 3.6% COULD COME FROM.
  //
  // Measured end to end, the windowed attention runs within 3.6-3.7% of
  // the ideal -- the dense kernel's own rate over the blocks it visits
  // -- so that is the whole kernel-side budget. Two things spend it, and
  // this says how much each is worth, from the geometry alone:
  //
  //   * PARTIAL blocks. The list is rounded outward to whole key
  //     blocks, so a block at a span's edge carries keys the mask
  //     forbids. Those are computed and then set to -inf.
  //   * The PREDICATE, which today runs on every visited block. A block
  //     that is entirely inside the window needs none of it, and if
  //     almost all of them are, splitting the list into full and partial
  //     (FlexAttention's shape) recovers most of the budget.
  //
  // Reported rather than asserted: these are properties of the released
  // window (chunk 5, radius 1) at a real geometry, and the point is the
  // size of the prize before anyone spends a day on it.
  struct Case { const char* name; int frames; int tpf; int glob; int qstep; };
  const Case cases[] = {
      {"960x544, 37 frames", 37, 510, 431, 1},
      {"960x544, 92 frames", 92, 510, 1053, 8},
  };
  const int BQ = 32, BK = 16;
  for (const Case& c : cases) {
    vdn::WindowMask m;
    m.tokens_per_frame = c.tpf;
    m.video_start = c.glob;
    m.num_frames = c.frames;
    m.anchors = vdn::AnchorFrames::kBoth;
    m.bounds = vdn::window_bounds(c.frames, 1, 5);
    m.seq_len = c.glob + c.frames * c.tpf;
    const vdn::BlockSpans bs = vdn::build_block_spans(m, BQ, BK);
    const int nq = (int)bs.off.size() - 1;

    long long visited = 0, full = 0, pairs = 0, allowed = 0;
    for (int qb = 0; qb < nq; qb += c.qstep) {
      const int r0 = qb * BQ, r1 = std::min(r0 + BQ, m.seq_len);
      for (int i = bs.off[(std::size_t)qb]; i < bs.off[(std::size_t)qb + 1];
           ++i) {
        const int k0 = bs.blocks[(std::size_t)i] * BK;
        const int k1 = std::min(k0 + BK, m.seq_len);
        bool all_ok = true;
        for (int r = r0; r < r1; ++r) {
          for (int k = k0; k < k1; ++k) {
            ++pairs;
            if (m.allows(r, k)) { ++allowed; }
            else { all_ok = false; }
          }
        }
        ++visited;
        if (all_ok) { ++full; }
      }
    }
    std::printf("[vdn_geometry] %-20s  %lld blocks sampled: %.1f%% FULL "
                "(need no predicate), %.1f%% of computed pairs are "
                "allowed\n", c.name, visited,
                100.0 * (double)full / (double)(visited ? visited : 1),
                100.0 * (double)allowed / (double)(pairs ? pairs : 1));
    EXPECT_TRUE(visited > 0 && allowed > 0);
  }
}
