// VDN-H3's linear branch, tap by tap, against the real checkpoint.
//
// The goldens are generated by rebuilding the chain out of the reference
// module's OWN submodules and then asserting that the rebuild equals
// br.forward() -- so the taps decompose the module rather than something
// adjacent, and a golden that pins a fiction fails at generation time.
// See ~/dock/dump/vpipe-test/vdn/gen_goldens.py branch.
//
// Checking taps rather than only the output is the point: this is a
// seven-stage chain ending in an RMSNorm and a sigmoid gate, both of
// which flatten magnitude errors, so an end-to-end rel-L2 can look
// respectable while a middle stage is wrong. The stage that fails names
// itself here.

#include "minitest.h"

#include "common/flex-data.h"
#include "generative-models/minimax-h3/vdn-geometry.h"
#include "generative-models/minimax-h3/vdn-delta-solve.h"
#include "generative-models/minimax-h3/vdn-linear-branch.h"

#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <map>
#include <string>
#include <vector>

using namespace vpipe;
using namespace vpipe::genai::minimax_h3;

namespace {

struct Golden {
  bool ok = false;
  int frames = 0, grid_h = 0, grid_w = 0, heads = 0, head_dim = 0;
  int hidden = 0, text_len = 0, chunk = 0, radius = 0;
  float text_state_scale = 0.5f;
  std::string anchor;
  std::vector<vdn::Bound> bounds;
  std::map<std::string, std::vector<float>> t;

  const float* get(const char* name) const
  {
    auto it = t.find(name);
    return it == t.end() ? nullptr : it->second.data();
  }
  std::size_t size(const char* name) const
  {
    auto it = t.find(name);
    return it == t.end() ? 0 : it->second.size();
  }
};

bool
read_bin_(const std::string& path, std::vector<float>* out)
{
  std::ifstream in(path, std::ios::binary | std::ios::ate);
  if (!in) { return false; }
  const std::streamsize n = in.tellg();
  if (n <= 0) { return false; }
  in.seekg(0);
  out->resize((std::size_t)n / sizeof(float));
  return (bool)in.read((char*)out->data(), n);
}

Golden
load_()
{
  Golden g;
  std::string dir;
  if (const char* e = std::getenv("VPIPE_VDN_BRANCH_GOLDEN")) { dir = e; }
  else if (const char* h = std::getenv("HOME")) {
    dir = std::string(h) + "/dock/dump/vpipe-test/vdn/branch";
  } else {
    return g;
  }
  std::ifstream mi(dir + "/meta.json");
  if (!mi) { return g; }
  FlexData meta = FlexData::from_json(mi);
  if (!meta.is_object()) { return g; }
  auto m = meta.as_object();
  g.frames   = (int)m.at("frames").as_int(0);
  g.grid_h   = (int)m.at("grid_h").as_int(0);
  g.grid_w   = (int)m.at("grid_w").as_int(0);
  g.heads    = (int)m.at("heads").as_int(0);
  g.head_dim = (int)m.at("head_dim").as_int(0);
  g.hidden   = (int)m.at("hidden").as_int(0);
  g.text_len = (int)m.at("text_len").as_int(0);
  g.chunk    = (int)m.at("chunk").as_int(0);
  g.radius   = (int)m.at("radius").as_int(0);
  g.text_state_scale = (float)m.at("text_state_scale").as_real(0.5);
  g.anchor   = std::string(m.at("anchor_frames").as_string(""));
  FlexData bo = m.at("bounds");
  auto ba = bo.as_array();
  for (std::size_t i = 0; i < ba.size(); ++i) {
    FlexData p = ba.at(i);
    auto pa = p.as_array();
    if (pa.size() == 2) {
      g.bounds.push_back({(int)pa.at(0).as_int(0), (int)pa.at(1).as_int(0)});
    }
  }
  FlexData ts = m.at("tensors");
  auto to = ts.as_object();
  for (auto entry : to) {
    std::vector<float> v;
    const std::string key(entry.first);
    if (!read_bin_(dir + "/" + key + ".bin", &v)) { return g; }
    g.t[key] = std::move(v);
  }
  g.ok = !g.t.empty();
  return g;
}

double
rel_l2_(const float* got, const float* want, std::size_t n)
{
  if (got == nullptr || want == nullptr || n == 0) { return -1.0; }
  double num = 0.0, den = 0.0;
  for (std::size_t i = 0; i < n; ++i) {
    const double d = (double)got[i] - (double)want[i];
    num += d * d;
    den += (double)want[i] * (double)want[i];
  }
  return den > 0.0 ? std::sqrt(num / den) : std::sqrt(num);
}

bool
check_(const char* stage, const float* got, const Golden& g, const char* name,
       double bar)
{
  const double e = rel_l2_(got, g.get(name), g.size(name));
  const bool ok = e >= 0.0 && e < bar;
  if (!ok) {
    std::printf("[vdn_branch] %-14s rel-L2 %.3e (bar %.0e, %zu values)\n",
                stage, e, bar, g.size(name));
  }
  return ok;
}

vdn::LinearBranchWeights
weights_(const Golden& g)
{
  vdn::LinearBranchWeights w;
  w.k_conv.spatial  = g.get("w_short_conv_k_sp_weight");
  w.k_conv.temporal = g.get("w_short_conv_k_tm_weight");
  w.v_conv.spatial  = g.get("w_short_conv_v_sp_weight");
  w.v_conv.temporal = g.get("w_short_conv_v_tm_weight");
  w.beta_proj     = g.get("w_beta_proj_weight");
  w.alpha_down    = g.get("w_alpha_down_weight");
  w.alpha_up      = g.get("w_alpha_up_weight");
  w.alpha_dt_bias = g.get("w_alpha_dt_bias");
  w.alpha_a_log   = g.get("w_alpha_A_log");
  w.gate_down     = g.get("w_output_gate_down_weight");
  w.gate_up_w     = g.get("w_output_gate_up_weight");
  w.gate_up_b     = g.get("w_output_gate_up_bias");
  w.norm          = g.get("w_norm_weight");
  return w;
}

}  // namespace

TEST(vdn_linear_branch, every_stage_matches_the_reference)
{
  const Golden g = load_();
  if (!g.ok) { return; }        // dock-side artifact; see gen_goldens.py
  ASSERT_TRUE(g.anchor == "both");
  const int F = g.frames, S = g.grid_h * g.grid_w;
  const int H = g.heads, d = g.head_dim;
  const int Fi = F - 2;                        // the anchors leave the input
  const std::size_t wide = (std::size_t)H * d;
  const std::size_t mat = (std::size_t)d * d;

  vdn::LinearBranchConfig cfg;
  cfg.heads = H;
  cfg.head_dim = d;
  cfg.hidden = g.hidden;
  cfg.text_state_scale = g.text_state_scale;
  const vdn::LinearBranchWeights w = weights_(g);

  const float* xin = g.get("xv") + (std::size_t)S * g.hidden;
  const std::size_t qoff = (std::size_t)S * wide;

  // --- 1. features
  std::vector<float> q((std::size_t)Fi * S * wide), k(q.size()), v(q.size());
  vdn::linear_features(g.get("q_raw") + qoff, Fi, g.grid_h, g.grid_w, H, d,
                       nullptr, true, q.data());
  vdn::linear_features(g.get("k_raw") + qoff, Fi, g.grid_h, g.grid_w, H, d,
                       &w.k_conv, true, k.data());
  vdn::linear_features(g.get("v_raw") + qoff, Fi, g.grid_h, g.grid_w, H, d,
                       &w.v_conv, false, v.data());
  EXPECT_TRUE(check_("features q", q.data(), g, "feat_q", 2e-6));
  EXPECT_TRUE(check_("features k", k.data(), g, "feat_k", 2e-6));
  EXPECT_TRUE(check_("features v", v.data(), g, "feat_v", 2e-6));

  // --- 2. beta
  std::vector<float> beta((std::size_t)Fi * S * H);
  vdn::branch_beta(xin, Fi * S, cfg, w.beta_proj, beta.data());
  EXPECT_TRUE(check_("beta", beta.data(), g, "beta", 1e-5));

  // --- 3. per-frame statistics
  std::vector<float> A((std::size_t)Fi * H * mat), B(A.size());
  vdn::frame_statistics(k.data(), v.data(), beta.data(), Fi, S, H, d,
                        A.data(), B.data());
  EXPECT_TRUE(check_("A", A.data(), g, "A", 1e-5));
  EXPECT_TRUE(check_("B", B.data(), g, "B", 1e-5));

  // --- 4. alpha (and the fp32 frame mean it rides on)
  std::vector<float> mean((std::size_t)Fi * g.hidden);
  std::vector<float> alpha((std::size_t)Fi * H * d);
  vdn::branch_alpha(xin, Fi, S, cfg, w, mean.data(), alpha.data());
  EXPECT_TRUE(check_("frame_mean", mean.data(), g, "frame_mean", 1e-6));
  EXPECT_TRUE(check_("alpha", alpha.data(), g, "alpha", 1e-5));

  // --- 5. the text state both scans start from
  std::vector<float> text((std::size_t)H * mat);
  ASSERT_TRUE(vdn::branch_text_state(g.get("text_x"), g.get("text_k_raw"),
                                     g.get("text_v_raw"), g.text_len, cfg, w,
                                     text.data()));
  EXPECT_TRUE(check_("text_state", text.data(), g, "text_state", 5e-5));

  // --- 6. the two scans
  std::vector<float> prefix((std::size_t)Fi * H * mat), suffix(prefix.size());
  ASSERT_TRUE(vdn::branch_scans(A.data(), B.data(), alpha.data(), Fi, H, d,
                                text.data(), prefix.data(), suffix.data()));
  EXPECT_TRUE(check_("prefix", prefix.data(), g, "prefix", 5e-5));
  EXPECT_TRUE(check_("suffix", suffix.data(), g, "suffix", 5e-5));

  // --- 7. gather + readout
  const std::vector<vdn::Bound> reb =
      vdn::rebase_for_anchor_skip(g.bounds, F);
  const vdn::GatherIndex idx = vdn::gather_indices(reb, Fi);
  std::vector<float> state(prefix.size());
  vdn::gather_linear_state(prefix.data(), suffix.data(), alpha.data(), idx,
                           Fi, H, d, d, true, text.data(), state.data());
  EXPECT_TRUE(check_("linear_state", state.data(), g, "linear_state", 5e-5));

  std::vector<float> rd((std::size_t)Fi * S * wide);
  vdn::branch_readout(q.data(), state.data(), xin, Fi, S, cfg, w, rd.data());
  EXPECT_TRUE(check_("readout", rd.data(), g, "readout_inner", 5e-5));
}

TEST(vdn_linear_branch, forward_matches_and_zeroes_the_anchor_rows)
{
  // The whole branch in one call, plus the property the softmax side
  // depends on: with anchor_frames "both" the two anchor frames'
  // readout rows are EXACTLY zero, not merely small. The softmax branch
  // makes those frames exact in both directions, so anything the linear
  // branch added there would be counted twice.
  const Golden g = load_();
  if (!g.ok) { return; }
  const int F = g.frames, S = g.grid_h * g.grid_w;
  const std::size_t wide = (std::size_t)g.heads * g.head_dim;

  vdn::LinearBranchConfig cfg;
  cfg.heads = g.heads;
  cfg.head_dim = g.head_dim;
  cfg.hidden = g.hidden;
  cfg.text_state_scale = g.text_state_scale;
  const vdn::LinearBranchWeights w = weights_(g);

  std::vector<float> out((std::size_t)F * S * wide);
  const bool ok = vdn::linear_branch_forward(
      g.get("xv"), g.get("q_raw"), g.get("k_raw"), g.get("v_raw"), F,
      g.grid_h, g.grid_w, g.bounds, g.get("text_x"), g.get("text_k_raw"),
      g.get("text_v_raw"), g.text_len, cfg, w, out.data());
  ASSERT_TRUE(ok);
  if (!ok) { return; }
  EXPECT_TRUE(check_("forward", out.data(), g, "readout", 5e-5));

  bool zero = true;
  for (std::size_t i = 0; i < (std::size_t)S * wide; ++i) {
    zero = zero && out[i] == 0.0f
           && out[((std::size_t)(F - 1) * S) * wide + i] == 0.0f;
  }
  EXPECT_TRUE(zero);
}

TEST(vdn_linear_branch, an_unsymmetrised_A_factorises_a_different_matrix)
{
  // The symmetrisation in frame_statistics is NOT exercised by the tap
  // test above, and saying so is the point of this one.
  //
  // A = sum_s beta k k^T is symmetric in exact arithmetic. This CPU
  // reference accumulates the (i,j) and (j,i) entries from the same
  // products in a different association, so its asymmetry sits below the
  // tap test's bar and removing the symmetrisation there changes
  // nothing measurable (checked by mutation). The step is not therefore
  // decoration: on the Metal path A comes out of a tensor-core GEMM
  // where the two triangles are computed by genuinely different
  // reductions, and the reference documents bf16 asymmetry large enough
  // to push the smallest eigenvalue of I + A below the 1 the maths
  // guarantees -- at which point cholesky, which reads ONE triangle,
  // factorises a matrix nobody meant.
  //
  // So pin the consequence where it is observable: perturb one triangle
  // by an amount a GEMM plausibly produces and show the factor moves.
  const int d = 32, S = 200;
  std::vector<float> a((std::size_t)d * d, 0.0f);
  unsigned seed = 99u;
  auto rnd = [&seed]() {
    seed = seed * 1664525u + 1013904223u;
    return (float)((seed >> 8) & 0xFFFF) / 32768.0f - 1.0f;
  };
  std::vector<float> k((std::size_t)d);
  for (int s = 0; s < S; ++s) {
    double n = 0.0;
    for (int i = 0; i < d; ++i) { k[i] = rnd() + 0.8f; n += k[i] * k[i]; }
    n = std::sqrt(n);
    for (int i = 0; i < d; ++i) { k[i] = (float)(k[i] / n); }
    const float beta = 0.5f + 0.25f * rnd();
    for (int i = 0; i < d; ++i) {
      for (int j = 0; j < d; ++j) {
        a[(std::size_t)i * d + j] += beta * k[i] * k[j];
      }
    }
  }
  std::vector<float> l_sym((std::size_t)d * d), l_asym(l_sym.size());
  ASSERT_TRUE(vdn::cholesky_lower(a.data(), d, l_sym.data()));

  // A GEMM-scale perturbation of the UPPER triangle only. cholesky reads
  // the lower one, so a correct implementation is unmoved -- and that is
  // precisely why an unsymmetrised A is silent: the discarded triangle
  // carries half the information about how wrong the kept one is.
  std::vector<float> upper = a;
  for (int i = 0; i < d; ++i) {
    for (int j = i + 1; j < d; ++j) {
      upper[(std::size_t)i * d + j] *= 1.001f;
    }
  }
  ASSERT_TRUE(vdn::cholesky_lower(upper.data(), d, l_asym.data()));
  EXPECT_TRUE(rel_l2_(l_asym.data(), l_sym.data(), l_sym.size()) < 1e-7);

  // Perturbing the LOWER triangle by the same amount DOES move it, which
  // is the same perturbation an unsymmetrised A would have landed there
  // half the time.
  std::vector<float> lower = a;
  for (int i = 0; i < d; ++i) {
    for (int j = 0; j < i; ++j) {
      lower[(std::size_t)i * d + j] *= 1.001f;
    }
  }
  ASSERT_TRUE(vdn::cholesky_lower(lower.data(), d, l_asym.data()));
  EXPECT_TRUE(rel_l2_(l_asym.data(), l_sym.data(), l_sym.size()) > 1e-4);
}

// ---- the branch on Metal ---------------------------------------------

#include "apple-silicon/metal-compute/compute-encoder.h"
#include "apple-silicon/metal-compute/compute-library.h"
#include "apple-silicon/metal-compute/metal-compute.h"
#include "apple-silicon/metal-compute/shared-buffer.h"
#include "common/session.h"

#include <cstring>

using namespace vpipe::metal_compute;

TEST(vdn_linear_branch, metal_frame_stats_match_the_cpu_oracle)
{
  // Checked on the REAL features and beta from the branch golden, not on
  // synthetic tensors: A's conditioning is what the solve downstream
  // depends on, and it is a property of real, strongly-correlated
  // patch keys. Random keys give a well-behaved A and would let a
  // precision mistake through.
  const Golden g = load_();
  if (!g.ok) { return; }
  Session s;
  MetalCompute* mc = s.metal_compute();
  if (mc == nullptr || !mc->valid()) { return; }
  ComputeLibrary lib = mc->load_library("vdn_branch");
  ComputeFunction stats = lib.function("vdn_frame_stats_f32");
  ComputeFunction sym = lib.function("vdn_symmetrise_f32");
  // An unvalidated ComputeFunction is a silent no-op.
  ASSERT_TRUE(stats.valid() && sym.valid());
  if (!stats.valid() || !sym.valid()) { return; }

  const int S = g.grid_h * g.grid_w, H = g.heads, d = g.head_dim;
  const int Fi = g.frames - 2;
  const std::size_t feat = (std::size_t)Fi * S * H * d;
  const std::size_t mats = (std::size_t)Fi * H * d * d;
  if (g.size("feat_k") != feat || g.size("beta") != (std::size_t)Fi * S * H) {
    EXPECT_TRUE(false);
    return;
  }

  SharedBuffer kb = mc->make_shared_buffer(feat * sizeof(float));
  SharedBuffer vb = mc->make_shared_buffer(feat * sizeof(float));
  SharedBuffer bb =
      mc->make_shared_buffer((std::size_t)Fi * S * H * sizeof(float));
  SharedBuffer ab = mc->make_shared_buffer(mats * sizeof(float));
  SharedBuffer bo = mc->make_shared_buffer(mats * sizeof(float));
  if (kb.empty() || ab.empty() || bo.empty()) {
    EXPECT_TRUE(false);
    return;
  }
  std::memcpy(kb.contents(), g.get("feat_k"), feat * sizeof(float));
  std::memcpy(vb.contents(), g.get("feat_v"), feat * sizeof(float));
  std::memcpy(bb.contents(), g.get("beta"),
              (std::size_t)Fi * S * H * sizeof(float));

  const unsigned tiles = (unsigned)((d + 31) / 32);
  {
    CommandStream stream = mc->make_command_stream();
    ComputeEncoder enc = stream.begin_compute();
    enc.set_function(stats);
    enc.set_buffer(0, kb);
    enc.set_buffer(1, vb);
    enc.set_buffer(2, bb);
    enc.set_buffer(3, ab);
    enc.set_buffer(4, bo);
    enc.set_constant(5, S);
    enc.set_constant(6, H);
    enc.set_constant(7, d);
    // fp32 features: the tight default the goldens were taken at.
    enc.set_buffer(8, kb); enc.set_buffer(9, vb); enc.set_buffer(10, bb);
    enc.set_constant(11, 0);
    enc.dispatch({tiles * 16, tiles * 16, (unsigned)(Fi * H)}, {16, 16, 1});
    enc.set_function(sym);
    enc.set_buffer(0, ab);
    enc.set_constant(1, d);
    enc.dispatch({(unsigned)((d + 31) / 32) * 32, (unsigned)(Fi * H), 1},
                 {32, 1, 1});
    enc.end();
    std::string err;
    ASSERT_TRUE(stream.commit().wait_ok(&err));
  }

  EXPECT_TRUE(check_("metal A", (const float*)ab.contents(), g, "A", 5e-6));
  EXPECT_TRUE(check_("metal B", (const float*)bo.contents(), g, "B", 5e-6));

  // A must come back SYMMETRIC to the bit, not merely close: the
  // Cholesky reads one triangle and the other is what says how wrong it
  // would otherwise be.
  const float* A = (const float*)ab.contents();
  bool exact = true;
  for (std::size_t m = 0; m < (std::size_t)Fi * H && exact; ++m) {
    const float* Am = A + m * (std::size_t)d * d;
    for (int i = 0; i < d && exact; ++i) {
      for (int j = i + 1; j < d; ++j) {
        if (Am[(std::size_t)i * d + j] != Am[(std::size_t)j * d + i]) {
          exact = false;
          break;
        }
      }
    }
  }
  EXPECT_TRUE(exact);

  // And the whole point of the fp32: I + A must factorise.
  std::vector<float> l((std::size_t)d * d);
  bool pd = true;
  for (std::size_t m = 0; m < (std::size_t)Fi * H; ++m) {
    pd = pd && vdn::cholesky_lower(A + m * (std::size_t)d * d, d, l.data());
  }
  EXPECT_TRUE(pd);
}

TEST(vdn_linear_branch, metal_readout_matches_the_cpu_oracle)
{
  // The gate and the readout on the GPU, against the same golden the CPU
  // reference is checked on -- so this is the reference's numbers, not
  // the port's reading of them. Uses the golden's own linear_state and
  // features, so a failure here is this stage and not an accumulation of
  // everything upstream.
  const Golden g = load_();
  if (!g.ok) { return; }
  Session s;
  MetalCompute* mc = s.metal_compute();
  if (mc == nullptr || !mc->valid()) { return; }
  ComputeLibrary lib = mc->load_library("vdn_branch");
  ComputeFunction gate_fn = lib.function("vdn_gate_f32");
  ComputeFunction read_fn = lib.function("vdn_readout_f32");
  ASSERT_TRUE(gate_fn.valid() && read_fn.valid());
  if (!gate_fn.valid() || !read_fn.valid()) { return; }

  const int S = g.grid_h * g.grid_w, H = g.heads, d = g.head_dim;
  const int Fi = g.frames - 2, tokens = Fi * S;
  const std::size_t wide = (std::size_t)H * d;
  const std::size_t nq = (std::size_t)tokens * wide;
  const std::size_t nstate = (std::size_t)Fi * H * d * d;
  const int hidden = g.hidden;

  SharedBuffer qb = mc->make_shared_buffer(nq * sizeof(float));
  SharedBuffer sb = mc->make_shared_buffer(nstate * sizeof(float));
  SharedBuffer xb =
      mc->make_shared_buffer((std::size_t)tokens * hidden * sizeof(float));
  SharedBuffer dwb =
      mc->make_shared_buffer((std::size_t)d * hidden * sizeof(float));
  SharedBuffer uwb = mc->make_shared_buffer(wide * (std::size_t)d
                                            * sizeof(float));
  SharedBuffer ubb = mc->make_shared_buffer(wide * sizeof(float));
  SharedBuffer gb = mc->make_shared_buffer(nq * sizeof(float));
  SharedBuffer nwb = mc->make_shared_buffer((std::size_t)d * sizeof(float));
  SharedBuffer ob = mc->make_shared_buffer(nq * sizeof(float));
  if (qb.empty() || sb.empty() || ob.empty() || uwb.empty()) {
    EXPECT_TRUE(false);
    return;
  }
  std::memcpy(qb.contents(), g.get("feat_q"), nq * sizeof(float));
  std::memcpy(sb.contents(), g.get("linear_state"), nstate * sizeof(float));
  std::memcpy(xb.contents(), g.get("xv") + (std::size_t)S * hidden,
              (std::size_t)tokens * hidden * sizeof(float));
  std::memcpy(dwb.contents(), g.get("w_output_gate_down_weight"),
              (std::size_t)d * hidden * sizeof(float));
  std::memcpy(uwb.contents(), g.get("w_output_gate_up_weight"),
              wide * (std::size_t)d * sizeof(float));
  std::memcpy(ubb.contents(), g.get("w_output_gate_up_bias"),
              wide * sizeof(float));
  std::memcpy(nwb.contents(), g.get("w_norm_weight"),
              (std::size_t)d * sizeof(float));

  const int outn = (int)wide;
  const float eps = 1e-6f;
  {
    CommandStream stream = mc->make_command_stream();
    ComputeEncoder enc = stream.begin_compute();
    enc.set_function(gate_fn);
    enc.set_buffer(0, xb);
    enc.set_buffer(1, dwb);
    enc.set_buffer(2, uwb);
    enc.set_buffer(3, ubb);
    enc.set_buffer(4, gb);
    enc.set_constant(5, hidden);
    enc.set_constant(6, d);
    enc.set_constant(7, outn);
    enc.set_buffer(8, xb);
    enc.set_constant(9, 0);           // fp32: the tight default
    enc.dispatch({(unsigned)tokens * 128, 1, 1}, {128, 1, 1});

    enc.set_function(read_fn);
    enc.set_buffer(0, qb);
    enc.set_buffer(1, sb);
    enc.set_buffer(2, gb);
    enc.set_buffer(3, nwb);
    enc.set_buffer(4, ob);
    enc.set_constant(5, S);
    enc.set_constant(6, H);
    enc.set_constant(7, d);
    enc.set_constant(8, eps);
    enc.set_buffer(9, ob);
    enc.set_constant(10, 0);          // fp32 out: the tight default
    enc.set_buffer(11, qb); enc.set_buffer(12, sb); enc.set_buffer(13, gb);
    enc.set_constant(14, 0);
    // Frame-aligned tiles: z is the frame, x the token tile within it.
    enc.dispatch({(unsigned)((S + 7) / 8) * 128, (unsigned)H,
                  (unsigned)Fi}, {128, 1, 1});
    enc.end();
    std::string err;
    ASSERT_TRUE(stream.commit().wait_ok(&err));
  }

  EXPECT_TRUE(check_("metal gate", (const float*)gb.contents(), g, "gate",
                     5e-6));
  EXPECT_TRUE(check_("metal readout", (const float*)ob.contents(), g,
                     "readout_inner", 1e-5));
}

TEST(vdn_linear_branch, metal_beta_alpha_and_gather_match_the_cpu_oracle)
{
  // The remaining branch stages. beta goes through the SAME kernel as
  // the gate with a zero bias and no bottleneck -- beta_proj really has
  // no bias, which is the fact that makes beta centre on 0.5 and the
  // solve unavoidable -- so this also checks that path of the kernel.
  const Golden g = load_();
  if (!g.ok) { return; }
  Session s;
  MetalCompute* mc = s.metal_compute();
  if (mc == nullptr || !mc->valid()) { return; }
  ComputeLibrary lib = mc->load_library("vdn_branch");
  ComputeFunction gate_fn = lib.function("vdn_gate_f32");
  ComputeFunction mean_fn = lib.function("vdn_frame_mean_f32");
  ComputeFunction alpha_fn = lib.function("vdn_alpha_f32");
  ComputeFunction bridge_fn = lib.function("vdn_alpha_bridge_f32");
  ComputeFunction gather_fn = lib.function("vdn_gather_f32");
  ASSERT_TRUE(gate_fn.valid() && mean_fn.valid() && alpha_fn.valid()
              && bridge_fn.valid() && gather_fn.valid());
  if (!gather_fn.valid()) { return; }

  const int S = g.grid_h * g.grid_w, H = g.heads, d = g.head_dim;
  const int Fi = g.frames - 2, tokens = Fi * S, hidden = g.hidden;
  const std::size_t mat = (std::size_t)d * d;

  auto buf = [&](std::size_t n) { return mc->make_shared_buffer(n * 4); };
  SharedBuffer xb = buf((std::size_t)tokens * hidden);
  std::memcpy(xb.contents(), g.get("xv") + (std::size_t)S * hidden,
              (std::size_t)tokens * hidden * 4);

  // --- beta, through the gate kernel with a zero bias
  SharedBuffer bpw = buf((std::size_t)H * hidden);
  SharedBuffer zbias = buf((std::size_t)H);
  SharedBuffer bout = buf((std::size_t)tokens * H);
  SharedBuffer dummy = buf(1);
  std::memcpy(bpw.contents(), g.get("w_beta_proj_weight"),
              (std::size_t)H * hidden * 4);
  std::memset(zbias.contents(), 0, (std::size_t)H * 4);

  // --- alpha
  SharedBuffer mean = buf((std::size_t)Fi * hidden);
  SharedBuffer adw = buf((std::size_t)d * hidden);
  SharedBuffer auw = buf((std::size_t)H * d * d);
  SharedBuffer adt = buf((std::size_t)H * d);
  SharedBuffer alg = buf((std::size_t)H);
  SharedBuffer aout = buf((std::size_t)Fi * H * d);
  std::memcpy(adw.contents(), g.get("w_alpha_down_weight"),
              (std::size_t)d * hidden * 4);
  std::memcpy(auw.contents(), g.get("w_alpha_up_weight"),
              (std::size_t)H * d * d * 4);
  std::memcpy(adt.contents(), g.get("w_alpha_dt_bias"),
              (std::size_t)H * d * 4);
  std::memcpy(alg.contents(), g.get("w_alpha_A_log"), (std::size_t)H * 4);

  // --- gather
  const std::vector<vdn::Bound> reb =
      vdn::rebase_for_anchor_skip(g.bounds, g.frames);
  const vdn::GatherIndex idx = vdn::gather_indices(reb, Fi);
  auto ibuf = [&](const std::vector<int>& v) {
    SharedBuffer b = mc->make_shared_buffer(v.size() * sizeof(int));
    std::memcpy(b.contents(), v.data(), v.size() * sizeof(int));
    return b;
  };
  auto cbuf = [&](const std::vector<char>& v) {
    std::vector<int> w(v.begin(), v.end());
    return ibuf(w);
  };
  SharedBuffer bidx = ibuf(idx.before_idx), aidx = ibuf(idx.after_idx);
  SharedBuffer hasb = cbuf(idx.has_before), hasa = cbuf(idx.has_after);
  SharedBuffer brb = ibuf(idx.bridge_before), bra = ibuf(idx.bridge_after);
  SharedBuffer fb = buf((std::size_t)Fi * H * d);
  SharedBuffer fa = buf((std::size_t)Fi * H * d);
  SharedBuffer prefix = buf((std::size_t)Fi * H * mat);
  SharedBuffer suffix = buf((std::size_t)Fi * H * mat);
  SharedBuffer text = buf((std::size_t)H * mat);
  SharedBuffer gout = buf((std::size_t)Fi * H * mat);
  std::memcpy(prefix.contents(), g.get("prefix"),
              (std::size_t)Fi * H * mat * 4);
  std::memcpy(suffix.contents(), g.get("suffix"),
              (std::size_t)Fi * H * mat * 4);
  std::memcpy(text.contents(), g.get("text_state"), (std::size_t)H * mat * 4);

  const int zero = 0, one = 1, outH = H, outHD = H * d;
  {
    CommandStream stream = mc->make_command_stream();
    ComputeEncoder enc = stream.begin_compute();
    enc.set_function(gate_fn);
    enc.set_buffer(0, xb);
    enc.set_buffer(1, dummy);
    enc.set_buffer(2, bpw);
    enc.set_buffer(3, zbias);
    enc.set_buffer(4, bout);
    enc.set_constant(5, hidden);
    enc.set_constant(6, zero);        // no bottleneck: direct, per head
    enc.set_constant(7, outH);
    enc.set_buffer(8, xb);
    enc.set_constant(9, 0);
    enc.dispatch({(unsigned)tokens * 128, 1, 1}, {128, 1, 1});

    enc.set_function(mean_fn);
    enc.set_buffer(0, xb);
    enc.set_buffer(1, mean);
    enc.set_constant(2, S);
    enc.set_constant(3, hidden);
    enc.set_buffer(4, xb);
    enc.set_constant(5, 0);
    enc.dispatch({(unsigned)hidden, (unsigned)Fi, 1}, {64, 1, 1});

    enc.set_function(alpha_fn);
    enc.set_buffer(0, mean);
    enc.set_buffer(1, adw);
    enc.set_buffer(2, auw);
    enc.set_buffer(3, adt);
    enc.set_buffer(4, alg);
    enc.set_buffer(5, aout);
    enc.set_constant(6, hidden);
    enc.set_constant(7, outH);
    enc.set_constant(8, d);
    enc.dispatch({(unsigned)Fi * 128, 1, 1}, {128, 1, 1});

    enc.set_function(bridge_fn);
    enc.set_buffer(0, aout);
    enc.set_buffer(1, brb);
    enc.set_buffer(2, bra);
    enc.set_buffer(3, fb);
    enc.set_buffer(4, fa);
    enc.set_constant(5, Fi);
    enc.set_constant(6, outHD);
    enc.dispatch({(unsigned)outHD, 1, 1}, {64, 1, 1});

    enc.set_function(gather_fn);
    enc.set_buffer(0, prefix);
    enc.set_buffer(1, suffix);
    enc.set_buffer(2, fb);
    enc.set_buffer(3, fa);
    enc.set_buffer(4, bidx);
    enc.set_buffer(5, aidx);
    enc.set_buffer(6, hasb);
    enc.set_buffer(7, hasa);
    enc.set_buffer(8, text);
    enc.set_buffer(9, gout);
    enc.set_constant(10, outH);
    enc.set_constant(11, d);
    enc.set_constant(12, one);
    enc.set_buffer(13, gout);        // fp32 out: the tight default
    enc.set_constant(14, 0);
    enc.dispatch({(unsigned)d * 128, (unsigned)H, (unsigned)Fi},
                 {128, 1, 1});
    enc.end();
    std::string err;
    ASSERT_TRUE(stream.commit().wait_ok(&err));
  }

  EXPECT_TRUE(check_("metal beta", (const float*)bout.contents(), g, "beta",
                     1e-5));
  EXPECT_TRUE(check_("metal frame_mean", (const float*)mean.contents(), g,
                     "frame_mean", 1e-5));
  EXPECT_TRUE(check_("metal alpha", (const float*)aout.contents(), g, "alpha",
                     1e-5));
  EXPECT_TRUE(check_("metal gather", (const float*)gout.contents(), g,
                     "linear_state", 5e-5));
}

TEST(vdn_linear_branch, metal_end_to_end_matches_the_reference)
{
  // The WHOLE branch on the GPU, from the backbone's raw q/k/v and the
  // hidden state to the gated readout, against the reference's own
  // output. Every earlier Metal test feeds one stage the golden's own
  // inputs, which is what makes a failure name its stage; this one feeds
  // each stage the PREVIOUS stage's output, which is the only way an
  // error that only appears under composition -- a layout that two
  // kernels disagree about, a buffer aliased across a dispatch -- can
  // show up at all.
  const Golden g = load_();
  if (!g.ok) { return; }
  Session s;
  MetalCompute* mc = s.metal_compute();
  if (mc == nullptr || !mc->valid()) { return; }
  ComputeLibrary br = mc->load_library("vdn_branch");
  ComputeLibrary so = mc->load_library("vdn_solve");
  struct {
    ComputeFunction sp, ta, gate, stats, sym, mean, alpha, bridge, gather;
    ComputeFunction readout, step, scale;
    ComputeFunction chol, trinv, invtr, gemm;
  } fn;
  fn.sp     = br.function("vdn_conv_spatial_f32");
  fn.ta     = br.function("vdn_temporal_act_f32");
  fn.gate   = br.function("vdn_gate_f32");
  fn.stats  = br.function("vdn_frame_stats_f32");
  fn.sym    = br.function("vdn_symmetrise_f32");
  fn.mean   = br.function("vdn_frame_mean_f32");
  fn.alpha  = br.function("vdn_alpha_f32");
  fn.bridge = br.function("vdn_alpha_bridge_f32");
  fn.gather = br.function("vdn_gather_f32");
  fn.readout = br.function("vdn_readout_f32");
  fn.step   = br.function("vdn_state_step_f32");
  fn.scale  = br.function("vdn_scale_f32");
  fn.chol   = so.function("vdn_cholesky_f32");
  fn.trinv  = so.function("vdn_trinv_f32");
  fn.invtr  = so.function("vdn_inv_and_transition_f32");
  fn.gemm   = so.function("vdn_gemm_nn_f32");
  ASSERT_TRUE(fn.sp.valid() && fn.ta.valid() && fn.gate.valid()
              && fn.stats.valid() && fn.sym.valid() && fn.mean.valid()
              && fn.alpha.valid() && fn.bridge.valid() && fn.gather.valid()
              && fn.readout.valid() && fn.step.valid() && fn.scale.valid()
              && fn.chol.valid() && fn.trinv.valid() && fn.invtr.valid()
              && fn.gemm.valid());
  if (!fn.step.valid() || !fn.gemm.valid()) { return; }

  const int gh = g.grid_h, gw = g.grid_w, S = gh * gw;
  const int H = g.heads, d = g.head_dim, hidden = g.hidden;
  const int Fi = g.frames - 2, tokens = Fi * S, Lt = g.text_len;
  const int C = H * d, K = 5;
  const std::size_t mat = (std::size_t)d * d;
  const std::size_t per = (std::size_t)H * mat;
  const std::size_t nfeat = (std::size_t)tokens * C;

  auto buf = [&](std::size_t n) { return mc->make_shared_buffer(n * 4); };
  auto up = [&](SharedBuffer& b, const float* src, std::size_t n) {
    std::memcpy(b.contents(), src, n * 4);
  };
  auto ibuf = [&](const std::vector<int>& v) {
    SharedBuffer b = mc->make_shared_buffer(v.size() * sizeof(int));
    std::memcpy(b.contents(), v.data(), v.size() * sizeof(int));
    return b;
  };

  // --- inputs, sliced to the frames the branch owns (the anchors are
  //     dropped from the INPUT, not masked afterwards)
  const std::size_t off_x = (std::size_t)S * hidden;
  const std::size_t off_q = (std::size_t)S * C;
  SharedBuffer xb = buf((std::size_t)tokens * hidden);
  SharedBuffer qraw = buf(nfeat), kraw = buf(nfeat), vraw = buf(nfeat);
  up(xb, g.get("xv") + off_x, (std::size_t)tokens * hidden);
  up(qraw, g.get("q_raw") + off_q, nfeat);
  up(kraw, g.get("k_raw") + off_q, nfeat);
  up(vraw, g.get("v_raw") + off_q, nfeat);

  SharedBuffer tx = buf((std::size_t)Lt * hidden);
  SharedBuffer tk = buf((std::size_t)Lt * C), tv = buf((std::size_t)Lt * C);
  up(tx, g.get("text_x"), (std::size_t)Lt * hidden);
  up(tk, g.get("text_k_raw"), (std::size_t)Lt * C);
  up(tv, g.get("text_v_raw"), (std::size_t)Lt * C);

  // --- weights
  SharedBuffer wksp = buf((std::size_t)C * K * K), wktm = buf((std::size_t)C * K);
  SharedBuffer wvsp = buf((std::size_t)C * K * K), wvtm = buf((std::size_t)C * K);
  up(wksp, g.get("w_short_conv_k_sp_weight"), (std::size_t)C * K * K);
  up(wktm, g.get("w_short_conv_k_tm_weight"), (std::size_t)C * K);
  up(wvsp, g.get("w_short_conv_v_sp_weight"), (std::size_t)C * K * K);
  up(wvtm, g.get("w_short_conv_v_tm_weight"), (std::size_t)C * K);
  SharedBuffer bpw = buf((std::size_t)H * hidden), zb = buf((std::size_t)H);
  up(bpw, g.get("w_beta_proj_weight"), (std::size_t)H * hidden);
  std::memset(zb.contents(), 0, (std::size_t)H * 4);
  SharedBuffer adw = buf((std::size_t)d * hidden), auw = buf((std::size_t)C * d);
  SharedBuffer adt = buf((std::size_t)C), alg = buf((std::size_t)H);
  up(adw, g.get("w_alpha_down_weight"), (std::size_t)d * hidden);
  up(auw, g.get("w_alpha_up_weight"), (std::size_t)C * d);
  up(adt, g.get("w_alpha_dt_bias"), (std::size_t)C);
  up(alg, g.get("w_alpha_A_log"), (std::size_t)H);
  SharedBuffer gdw = buf((std::size_t)d * hidden), guw = buf((std::size_t)C * d);
  SharedBuffer gub = buf((std::size_t)C), nw = buf((std::size_t)d);
  up(gdw, g.get("w_output_gate_down_weight"), (std::size_t)d * hidden);
  up(guw, g.get("w_output_gate_up_weight"), (std::size_t)C * d);
  up(gub, g.get("w_output_gate_up_bias"), (std::size_t)C);
  up(nw, g.get("w_norm_weight"), (std::size_t)d);

  // --- scratch
  SharedBuffer qf = buf(nfeat), kf = buf(nfeat), vf = buf(nfeat);
  SharedBuffer tmp = buf(nfeat);
  SharedBuffer beta = buf((std::size_t)tokens * H);
  SharedBuffer A = buf((std::size_t)Fi * per), B = buf((std::size_t)Fi * per);
  SharedBuffer mean = buf((std::size_t)Fi * hidden);
  SharedBuffer alpha = buf((std::size_t)Fi * H * d);
  SharedBuffer L = buf((std::size_t)Fi * per), Li = buf((std::size_t)Fi * per);
  SharedBuffer inv = buf((std::size_t)Fi * per);
  SharedBuffer tr = buf((std::size_t)Fi * per), inj = buf((std::size_t)Fi * per);
  SharedBuffer prefix = buf((std::size_t)Fi * per);
  SharedBuffer suffix = buf((std::size_t)Fi * per);
  SharedBuffer fb = buf((std::size_t)Fi * H * d);
  SharedBuffer fa = buf((std::size_t)Fi * H * d);
  SharedBuffer state = buf((std::size_t)Fi * per);
  SharedBuffer gateb = buf(nfeat), out = buf(nfeat);
  SharedBuffer fail = mc->make_shared_buffer(sizeof(unsigned));
  std::memset(fail.contents(), 0, sizeof(unsigned));
  // text scratch
  SharedBuffer tkf = buf((std::size_t)Lt * C), tvf = buf((std::size_t)Lt * C);
  SharedBuffer tbeta = buf((std::size_t)Lt * H);
  SharedBuffer tA = buf(per), tB = buf(per), tL = buf(per), tLi = buf(per);
  SharedBuffer tInv = buf(per), tTr = buf(per), tState = buf(per);
  SharedBuffer ones = buf((std::size_t)H * d);
  {
    float* o = (float*)ones.contents();
    for (std::size_t i = 0; i < (std::size_t)H * d; ++i) { o[i] = 1.0f; }
  }

  const std::vector<vdn::Bound> reb =
      vdn::rebase_for_anchor_skip(g.bounds, g.frames);
  const vdn::GatherIndex idx = vdn::gather_indices(reb, Fi);
  std::vector<int> hb(idx.has_before.begin(), idx.has_before.end());
  std::vector<int> ha(idx.has_after.begin(), idx.has_after.end());
  SharedBuffer bidx = ibuf(idx.before_idx), aidx = ibuf(idx.after_idx);
  SharedBuffer hasb = ibuf(hb), hasa = ibuf(ha);
  SharedBuffer brb = ibuf(idx.bridge_before), bra = ibuf(idx.bridge_after);

  const int zero = 0, one = 1, outH = H, outC = C, HD = H * d;
  const int nfi = Fi, tokens_i = tokens;
  const float eps = 1e-6f, half = g.text_state_scale;
  const int per_i = (int)per;

  CommandStream stream = mc->make_command_stream();
  ComputeEncoder enc = stream.begin_compute();
  const unsigned tiles = (unsigned)((d + 31) / 32);

  auto features = [&](SharedBuffer& src, SharedBuffer& wsp, SharedBuffer& wtm,
                      SharedBuffer& dst, bool conv, bool l2, int frames,
                      int spf, int gh_, int gw_) {
    if (conv) {
      enc.set_function(fn.sp);
      enc.set_buffer(0, src);
      enc.set_buffer(1, wsp);
      enc.set_buffer(2, tmp);
      enc.set_constant(3, frames);
      enc.set_constant(4, gh_);
      enc.set_constant(5, gw_);
      enc.set_constant(6, outC);
      enc.set_constant(7, K);
      // The strided-source slots at their TIGHT defaults. Always bound:
      // an unbound Metal buffer is not reliably null and an unbound
      // constant is not reliably zero, so leaving them out reads garbage
      // strides rather than falling back to anything.
      enc.set_buffer(8, src);
      enc.set_constant(9, 0);
      enc.set_constant(10, outC);
      enc.set_constant(11, d);
      enc.set_constant(12, d);
      // Cells per thread -- see VB_CONV_NX. The kernel checks it, so a
      // stale value here is slow and not wrong.
      const int crun = 8;
      enc.set_constant(13, crun);
      const int cnxg = (gw_ + crun - 1) / crun;
      enc.set_buffer(14, tmp);         // fp32 out: the tight default
      enc.set_constant(15, 0);
      enc.dispatch({(unsigned)(frames * gh_ * cnxg * C), 1, 1},
                   {256, 1, 1});
    }
    const int use_t = conv ? 1 : 0, l2i = l2 ? 1 : 0;
    enc.set_function(fn.ta);
    enc.set_buffer(0, conv ? tmp : src);
    enc.set_buffer(1, wtm);
    enc.set_buffer(2, dst);
    enc.set_constant(3, frames);
    enc.set_constant(4, spf);
    enc.set_constant(5, outH);
    enc.set_constant(6, d);
    enc.set_constant(7, K);
    enc.set_constant(8, use_t);
    enc.set_constant(9, l2i);
    const int fbase = 0, ftot = frames, obase = 0;
    enc.set_constant(10, fbase);
    enc.set_constant(11, ftot);
    enc.set_constant(12, obase);
    enc.set_buffer(13, conv ? tmp : src);
    enc.set_constant(14, 0);
    enc.set_constant(15, outC);
    enc.set_constant(16, d);
    enc.set_buffer(17, dst);
    enc.set_constant(18, 0);
    enc.dispatch({(unsigned)(frames * spf) * 128, (unsigned)H, 1},
                 {128, 1, 1});
  };
  auto sigmoid_proj = [&](SharedBuffer& x, SharedBuffer& w, SharedBuffer& bias,
                          SharedBuffer& dst, int rows, int outn, int bneck,
                          SharedBuffer& down) {
    enc.set_function(fn.gate);
    enc.set_buffer(0, x);
    enc.set_buffer(1, down);
    enc.set_buffer(2, w);
    enc.set_buffer(3, bias);
    enc.set_buffer(4, dst);
    enc.set_constant(5, hidden);
    enc.set_constant(6, bneck);
    enc.set_constant(7, outn);
    enc.set_buffer(8, x);
    enc.set_constant(9, 0);
    enc.dispatch({(unsigned)rows * 128, 1, 1}, {128, 1, 1});
  };
  auto stats = [&](SharedBuffer& kk, SharedBuffer& vv, SharedBuffer& bb,
                   SharedBuffer& aa, SharedBuffer& bo, int spf, int batch) {
    enc.set_function(fn.stats);
    enc.set_buffer(0, kk);
    enc.set_buffer(1, vv);
    enc.set_buffer(2, bb);
    enc.set_buffer(3, aa);
    enc.set_buffer(4, bo);
    enc.set_constant(5, spf);
    enc.set_constant(6, outH);
    enc.set_constant(7, d);
    enc.set_buffer(8, kk); enc.set_buffer(9, vv); enc.set_buffer(10, bb);
    enc.set_constant(11, 0);
    enc.dispatch({tiles * 16, tiles * 16, (unsigned)batch}, {16, 16, 1});
    enc.set_function(fn.sym);
    enc.set_buffer(0, aa);
    enc.set_constant(1, d);
    enc.dispatch({(unsigned)((d + 31) / 32) * 32, (unsigned)batch, 1},
                 {32, 1, 1});
  };
  auto solve = [&](SharedBuffer& aa, SharedBuffer& al, SharedBuffer& bo,
                   SharedBuffer& ll, SharedBuffer& lli, SharedBuffer& iv,
                   SharedBuffer& trn, SharedBuffer& ij, int batch) {
    enc.set_function(fn.chol);
    enc.set_buffer(0, aa);
    enc.set_buffer(1, ll);
    enc.set_constant(2, d);
    enc.set_buffer(3, fail);
    enc.dispatch({(unsigned)batch * 128, 1, 1}, {128, 1, 1});
    enc.set_function(fn.trinv);
    enc.set_buffer(0, ll);
    enc.set_buffer(1, lli);
    enc.set_constant(2, d);
    enc.dispatch({tiles * 128, (unsigned)batch, 1}, {128, 1, 1});
    enc.set_function(fn.invtr);
    enc.set_buffer(0, lli);
    enc.set_buffer(1, al);
    enc.set_buffer(2, iv);
    enc.set_buffer(3, trn);
    enc.set_constant(4, d);
    enc.dispatch({tiles * 16, tiles * 16, (unsigned)batch}, {16, 16, 1});
    enc.set_function(fn.gemm);
    enc.set_buffer(0, bo);
    enc.set_buffer(1, iv);
    enc.set_buffer(2, ij);
    enc.set_constant(3, d);
    enc.set_constant(4, d);
    enc.set_constant(5, d);
    enc.dispatch({tiles * 16, tiles * 16, (unsigned)batch}, {16, 16, 1});
  };

  // --- 1. features (video), 2. beta
  features(qraw, wksp, wktm, qf, false, true, Fi, S, gh, gw);
  features(kraw, wksp, wktm, kf, true, true, Fi, S, gh, gw);
  features(vraw, wvsp, wvtm, vf, true, false, Fi, S, gh, gw);
  sigmoid_proj(xb, bpw, zb, beta, tokens_i, outH, zero, zb);

  // --- 3. per-frame statistics
  stats(kf, vf, beta, A, B, S, Fi * H);

  // --- 4. alpha
  enc.set_function(fn.mean);
  enc.set_buffer(0, xb);
  enc.set_buffer(1, mean);
  enc.set_constant(2, S);
  enc.set_constant(3, hidden);
  enc.set_buffer(4, xb);
  enc.set_constant(5, 0);
  enc.dispatch({(unsigned)hidden, (unsigned)Fi, 1}, {64, 1, 1});
  enc.set_function(fn.alpha);
  enc.set_buffer(0, mean);
  enc.set_buffer(1, adw);
  enc.set_buffer(2, auw);
  enc.set_buffer(3, adt);
  enc.set_buffer(4, alg);
  enc.set_buffer(5, alpha);
  enc.set_constant(6, hidden);
  enc.set_constant(7, outH);
  enc.set_constant(8, d);
  enc.dispatch({(unsigned)Fi * 128, 1, 1}, {128, 1, 1});

  // --- 5. the text state: the prompt as ONE chunk, alpha = 1, halved
  features(tk, wksp, wktm, tkf, false, true, 1, Lt, 1, Lt);
  features(tv, wvsp, wvtm, tvf, false, false, 1, Lt, 1, Lt);
  sigmoid_proj(tx, bpw, zb, tbeta, Lt, outH, zero, zb);
  stats(tkf, tvf, tbeta, tA, tB, Lt, H);
  solve(tA, ones, tB, tL, tLi, tInv, tTr, tState, H);
  enc.set_function(fn.scale);
  enc.set_buffer(0, tState);
  enc.set_constant(1, per_i);
  enc.set_constant(2, half);
  enc.dispatch({(unsigned)per, 1, 1}, {256, 1, 1});

  // --- 6. the solve on the frames, then the two scans
  solve(A, alpha, B, L, Li, inv, tr, inj, Fi * H);
  auto step = [&](const SharedBuffer& in, int f, SharedBuffer& bank) {
    enc.set_function(fn.step);
    enc.set_buffer(0, in);
    enc.set_buffer(1, tr, (std::size_t)f * per * 4);
    enc.set_buffer(2, inj, (std::size_t)f * per * 4);
    enc.set_buffer(3, bank, (std::size_t)f * per * 4);
    enc.set_constant(4, d);
    enc.dispatch({tiles * 16, tiles * 16, (unsigned)H}, {16, 16, 1});
  };
  for (int f = 0; f < Fi; ++f) {
    if (f == 0) { step(tState, 0, prefix); }
    else {
      enc.set_function(fn.step);
      enc.set_buffer(0, prefix, (std::size_t)(f - 1) * per * 4);
      enc.set_buffer(1, tr, (std::size_t)f * per * 4);
      enc.set_buffer(2, inj, (std::size_t)f * per * 4);
      enc.set_buffer(3, prefix, (std::size_t)f * per * 4);
      enc.set_constant(4, d);
      enc.dispatch({tiles * 16, tiles * 16, (unsigned)H}, {16, 16, 1});
    }
  }
  for (int f = Fi - 1; f >= 0; --f) {
    if (f == Fi - 1) { step(tState, f, suffix); }
    else {
      enc.set_function(fn.step);
      enc.set_buffer(0, suffix, (std::size_t)(f + 1) * per * 4);
      enc.set_buffer(1, tr, (std::size_t)f * per * 4);
      enc.set_buffer(2, inj, (std::size_t)f * per * 4);
      enc.set_buffer(3, suffix, (std::size_t)f * per * 4);
      enc.set_constant(4, d);
      enc.dispatch({tiles * 16, tiles * 16, (unsigned)H}, {16, 16, 1});
    }
  }

  // --- 7. bridge, gather, gate, readout
  enc.set_function(fn.bridge);
  enc.set_buffer(0, alpha);
  enc.set_buffer(1, brb);
  enc.set_buffer(2, bra);
  enc.set_buffer(3, fb);
  enc.set_buffer(4, fa);
  enc.set_constant(5, nfi);
  enc.set_constant(6, HD);
  enc.dispatch({(unsigned)HD, 1, 1}, {64, 1, 1});
  enc.set_function(fn.gather);
  enc.set_buffer(0, prefix);
  enc.set_buffer(1, suffix);
  enc.set_buffer(2, fb);
  enc.set_buffer(3, fa);
  enc.set_buffer(4, bidx);
  enc.set_buffer(5, aidx);
  enc.set_buffer(6, hasb);
  enc.set_buffer(7, hasa);
  enc.set_buffer(8, tState);
  enc.set_buffer(9, state);
  enc.set_constant(10, outH);
  enc.set_constant(11, d);
  enc.set_constant(12, one);
  enc.set_buffer(13, state);
  enc.set_constant(14, 0);
  enc.dispatch({(unsigned)d * 128, (unsigned)H, (unsigned)Fi}, {128, 1, 1});
  sigmoid_proj(xb, guw, gub, gateb, tokens_i, outC, d, gdw);
  enc.set_function(fn.readout);
  enc.set_buffer(0, qf);
  enc.set_buffer(1, state);
  enc.set_buffer(2, gateb);
  enc.set_buffer(3, nw);
  enc.set_buffer(4, out);
  enc.set_constant(5, S);
  enc.set_constant(6, outH);
  enc.set_constant(7, d);
  enc.set_constant(8, eps);
  enc.set_buffer(9, out);
  enc.set_constant(10, 0);
  enc.set_buffer(11, qf); enc.set_buffer(12, state);
  enc.set_buffer(13, gateb);
  enc.set_constant(14, 0);
  enc.dispatch({(unsigned)((S + 7) / 8) * 128, (unsigned)H, (unsigned)Fi},
               {128, 1, 1});
  enc.end();
  std::string err;
  ASSERT_TRUE(stream.commit().wait_ok(&err));
  EXPECT_TRUE(*(const unsigned*)fail.contents() == 0u);

  // MEASURED 3.2e-07 for the whole chain -- features, a 128-deep
  // Cholesky and triangular inverse, a serial scan over frames, the
  // gather and the readout -- so composition costs essentially nothing
  // over the single-stage bars above and the loose bar this started with
  // was a guess, not a measurement. 1e-5 leaves room for fp32 variation
  // across drivers while staying four orders below the 1e-1 a wrong
  // operator produces.
  EXPECT_TRUE(check_("metal e2e", (const float*)out.contents(), g,
                     "readout_inner", 1e-5));
}
