# embed-metallib.cmake -- `cmake -P` script that reads a `.metallib`
# file as bytes and writes a generated `.cc` TU. The TU registers
# the bytes with MetalCompute's process-wide embedded registry at
# static-init time via a Meyers-singleton store, so MetalCompute::
# load_library(KERNEL_NAME) can later resolve the bytes without an
# on-disk file.
#
# Required -D inputs:
#   KERNEL_NAME -- the symbolic name MetalCompute::load_library uses
#   INPUT       -- absolute path to the source .metallib file
#   OUTPUT      -- absolute path to write the generated .cc file

if(NOT DEFINED KERNEL_NAME)
  message(FATAL_ERROR "embed-metallib.cmake: -D KERNEL_NAME=... required")
endif()
if(NOT DEFINED INPUT)
  message(FATAL_ERROR "embed-metallib.cmake: -D INPUT=... required")
endif()
if(NOT DEFINED OUTPUT)
  message(FATAL_ERROR "embed-metallib.cmake: -D OUTPUT=... required")
endif()

file(READ "${INPUT}" BYTES HEX)
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," CSV "${BYTES}")

file(WRITE "${OUTPUT}"
"// Auto-generated by embed-metallib.cmake. Do not edit.
//
// Embeds the compiled metallib bytes for kernel \"${KERNEL_NAME}\"
// into libvpipe.dylib and registers them with MetalCompute's
// embedded library registry at static-init time.

#include <cstddef>

namespace vpipe::metal_compute::_embedded {
void register_embedded_metallib(const char* name,
                                const unsigned char* data,
                                std::size_t size);
}

namespace {

alignas(8) const unsigned char kBytes_${KERNEL_NAME}[] = {
${CSV}
};

struct Reg_${KERNEL_NAME} {
  Reg_${KERNEL_NAME}() {
    ::vpipe::metal_compute::_embedded::register_embedded_metallib(
        \"${KERNEL_NAME}\",
        kBytes_${KERNEL_NAME},
        sizeof(kBytes_${KERNEL_NAME}));
  }
};

const Reg_${KERNEL_NAME} g_reg_${KERNEL_NAME};

}  // namespace
")
