# vpipe-embed-metallib.cmake -- `cmake -P` script (shipped with the vpipe
# plugin SDK) that reads a compiled `.metallib` and emits a `.cc` TU
# exposing its bytes as two ORDINARY exported symbols:
#   extern "C" const unsigned char <NAME>_metallib[];
#   extern "C" const unsigned long <NAME>_metallib_len;
# A plugin passes these to ctx->register_metal_library("<NAME>", ...) at
# load time. Unlike libvpipe's internal embed step, this does NOT self-
# register into any private registry -- it targets the public runtime API.
#
# Required -D inputs:
#   NAME   -- symbol stem + the runtime library name
#   INPUT  -- absolute path to the source .metallib
#   OUTPUT -- absolute path to write the generated .cc

if(NOT DEFINED NAME)
  message(FATAL_ERROR "vpipe-embed-metallib.cmake: -D NAME=... required")
endif()
if(NOT DEFINED INPUT)
  message(FATAL_ERROR "vpipe-embed-metallib.cmake: -D INPUT=... required")
endif()
if(NOT DEFINED OUTPUT)
  message(FATAL_ERROR "vpipe-embed-metallib.cmake: -D OUTPUT=... required")
endif()

file(READ "${INPUT}" BYTES HEX)
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," CSV "${BYTES}")

file(WRITE "${OUTPUT}"
"// Auto-generated by vpipe-embed-metallib.cmake. Do not edit.
//
// Embeds the compiled metallib bytes for \"${NAME}\" as two exported
// symbols a vpipe plugin registers at load via register_metal_library.

#include <cstddef>

extern \"C\" {
alignas(8) const unsigned char ${NAME}_metallib[] = {
${CSV}
};
const unsigned long ${NAME}_metallib_len = sizeof(${NAME}_metallib);
}
")
