#ifndef UI_VIEW_REGISTRY_H
#define UI_VIEW_REGISTRY_H

#include "interfaces/ui-view-intf.h"

#include <cstddef>
#include <functional>
#include <memory>
#include <mutex>
#include <string>
#include <string_view>
#include <unordered_map>
#include <vector>

namespace vpipe {

// Process-wide catalogue of stage-provided GUI views (see
// interfaces/ui-view-intf.h) and the front-end asset bytes that back
// them. The registry is the BACKEND side of the split: a stage declares
// its panel here, in C++, and its JavaScript/CSS is embedded into
// libvpipe alongside it -- the front-end application discovers both at
// runtime instead of hard-coding either.
//
// Mirrors StageRegistry: a singleton populated at static-init time from
// each view's own translation unit (VPIPE_REGISTER_UI_VIEW), so a view
// registers whether or not anything references it, and a plugin .dylib
// that links libvpipe contributes to the same catalogue.

// A view's declaration. Instances have static storage duration (the
// registry keeps pointers), exactly like StageSpec.
struct UiViewSpec {
  // Panel type id -- unique process-wide, and the key the front end
  // uses to mount and to persist a saved layout. Lowercase-hyphen, by
  // convention matching the owning stage's kTypeName.
  std::string_view id;

  // The stage type this view presents, or empty for a view that is not
  // tied to one. Purely informational: the front end shows it, and it
  // lets a client hide views whose stage isn't built into this binary.
  std::string_view stage_type;

  // URL path of the ES module implementing the view, as registered in
  // the asset table below (e.g. "/ui/preview/preview-view.js"). The
  // module must export `mount(body, actions, ctx)`; see
  // ui/sdk/view-channel.js for the contract.
  std::string_view module;

  // Optional stylesheet asset path, injected once before first mount.
  // Empty when the view needs no CSS of its own.
  std::string_view styles;

  // Message-catalogue key for the panel's label (resolved by the front
  // end against the strings the module exports), plus the host icon
  // name to show beside it.
  std::string_view label_key;
  std::string_view icon;

  // Factory for the per-panel backend. Called once per mounted view;
  // the returned backend is owned by the caller and destroyed when the
  // panel closes. May be null for a view that needs no backend (a pure
  // client-side panel).
  std::unique_ptr<UiViewBackendIntf> (*make_backend)(UiViewHostIntf&)
      = nullptr;
};

// One embedded front-end file: `path` is the URL it is served at,
// `data`/`size` the bytes. Generated by ui/cmake/embed-ui-assets.cmake.
struct UiViewAsset {
  std::string_view     path;
  const unsigned char* data = nullptr;
  std::size_t          size = 0;
};

class UiViewRegistry {
public:
  static UiViewRegistry& get() noexcept;

  // Declare a view. First registration of an id wins (a duplicate is
  // ignored rather than fatal, matching StageRegistry's behaviour on
  // duplicate-include footguns). `spec` must have static storage.
  void register_view(const UiViewSpec* spec) noexcept;

  const UiViewSpec* find(std::string_view id) const noexcept;

  // Every registered view, in registration order.
  std::vector<const UiViewSpec*> all() const;

  // Publish a block of embedded assets. `assets` must have static
  // storage duration (the registry keeps the pointer, not a copy).
  void register_assets(const UiViewAsset* assets, std::size_t n) noexcept;

  // Look up an asset by its URL path, or nullptr. Paths are matched
  // exactly, including the leading '/'.
  const UiViewAsset* find_asset(std::string_view path) const noexcept;

private:
  UiViewRegistry() = default;

  struct StringHash {
    using is_transparent = void;
    std::size_t operator()(std::string_view sv) const noexcept
    { return std::hash<std::string_view>{}(sv); }
    std::size_t operator()(const std::string& s) const noexcept
    { return std::hash<std::string_view>{}(s); }
  };
  struct StringEq {
    using is_transparent = void;
    bool operator()(std::string_view a, std::string_view b)
      const noexcept { return a == b; }
    bool operator()(const std::string& a, std::string_view b)
      const noexcept { return a == b; }
    bool operator()(std::string_view a, const std::string& b)
      const noexcept { return a == b; }
    bool operator()(const std::string& a, const std::string& b)
      const noexcept { return a == b; }
  };

  std::vector<const UiViewSpec*> _views;
  std::unordered_map<std::string, const UiViewSpec*,
                     StringHash, StringEq> _by_id;
  std::unordered_map<std::string, const UiViewAsset*,
                     StringHash, StringEq> _assets;
  mutable std::mutex _mu;
};

// Register a view's file-static UiViewSpec at static-init time. Place
// at namespace scope in the view's .cc, exactly as VPIPE_REGISTER_SPEC
// is placed in a stage's:
//
//   const UiViewSpec kView{ .id = "preview", ... };
//   VPIPE_REGISTER_UI_VIEW(preview, kView)
//
// `TAG` only names the anonymous-namespace initializer (it must be a
// valid identifier); `SPEC` must have static storage duration. Do NOT
// remove this under "looks unused" -- without it the view is never
// discoverable, since nothing references it by symbol.
#define VPIPE_REGISTER_UI_VIEW(TAG, SPEC)                              \
  namespace { const auto _vpipe_ui_view_reg_##TAG = [] {               \
    ::vpipe::UiViewRegistry::get().register_view(&(SPEC));             \
    return 0; }(); }

}

#endif
